[package]
name = "rustorm"
version = "0.10.8"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A complete rewrite of rustorm"
repository = "https://github.com/ivanceras/rustorm"
documentation = "https://docs.rs/rustorm"
keywords = ["orm", "postgresql", "sqlite"]

[dependencies]
log = "0.4"
postgres = {version = "0.15.1",features = ["with-uuid","with-chrono","with-time","with-openssl","with-geo","with-bit-vec", "with-serde_json"], optional = true}
r2d2_postgres = {version = "0.14.0", optional = true}
postgres-shared = {version = "0.4.0", optional = true}
openssl = {version = "0.9.23", optional = true}
r2d2 = "0.8"
url = "1.5"
cfg-if = "0.1.2"
uuid = "0.5.1"
chrono = "0.4.0"
sqlite3 = {version = "0.24.0", optional = true}
r2d2-sqlite3 = {version = "0.1.1", optional = true}
#mysql = {version = "12.0.3", optional = true}
#oci_rs = {version = "0.5.0", optional = true}
#tiberius = {version = "0.2.2", optional = true}
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
byteorder = "1.0"
bigdecimal = "0.0.14"
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
meval = "0.1.0"
tree_magic = "0.2"
base64 = "0.9"
geo = "0.4"
time = "0.1.14"

[dependencies.rustorm_dao]
version = "0.1.8"

[dependencies.rustorm_codegen]
version = "0.1.8"

[features]
#default = ["with-postgres"]
with-postgres = ["postgres", "r2d2_postgres", "postgres-shared", "openssl"]
#with-mysql = ["mysql"]
with-sqlite = ["sqlite3","r2d2-sqlite3"]
#with-oracle = ["oci_rs"]
#with-mssql = ["tiberius"]

